use_frameworks!

target 'LateralTableViewCell_Example' do
  pod 'LateralTableViewCell', :path => '../'

  target 'LateralTableViewCell_Tests' do
    inherit! :search_paths
    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'

  end
end
